// USER ACTIONS
export const LOG_OUT = 'LOG_OUT';
export const SET_PROVIDER = 'SET_PROVIDER';

// CONTENT ACTIONS
export const GET_ALL_CONTENT = 'GET_ALL_CONTENT';
export const GET_ALL_CONTENT_SUCCESS = 'GET_ALL_CONTENT_SUCCESS';
export const GET_ALL_CONTENT_FAIL = 'GET_ALL_CONTENT_FAIL'; 
export const GET_ONE_CONTENT = 'GET_ONE_CONTENT';
export const GET_ONE_CONTENT_SUCCESS = 'GET_ONE_CONTENT_SUCCESS';
export const GET_ONE_CONTENT_FAIL = 'GET_ONE_CONTENT_FAIL';
export const UPLOAD_REQUESTED = 'UPLOAD_REQUESTED';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';  
export const UPLOAD_FAIL = 'UPLOAD_FAIL'; 
